# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Extra step requied for private beta .. 
#     - name: Checkout the action from a private repository
#       uses: actions/checkout@v2
#       with:
#         repository: aws-actions/codeguru-reviewer
#         ref: refs/heads/main
#         ssh-key: ${{ secrets.SSH_KEY }}
#         path: ./.github/actions/codeguru-reviewer
       
    # Extra step requied for private beta .. 
    - name: Checkout the action from a private repository
      uses: actions/checkout@v2
      with:
        repository: vdinesh90/codeguru-reviewer
        ref: main
#         ssh-key: ${{ secrets.SSH_KEY_TEST }}
        token: ${{ secrets.PAT }}
        

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2 #AWS region where you want to use CodeGuru

#     - name: AWS CodeGuru Reviewer Security Scanner
#       uses: ./.github/actions/codeguru-reviewer 
#       with:
#         src-root: src/main/java # Java source code root
#         build-root: target # build artifact(s) directory
    - name: ECR login
      uses: aws-actions/amazon-ecr-login@v1
      
    - name: Docker pull
      run: docker pull 758588794794.dkr.ecr.us-west-2.amazonaws.com/cg-private:latest 
    
    - name: AWS CodeGuru Reviewer Security Scanner
      uses: ./
      with:
        src-root: . # Java source code root
        build-root: target # build artifact(s) directory
        

    - name: Upload review result
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: codeguru-results.sarif.json
